---
title: "Simple Multiple Regression"
output: html_document
date: "`r Sys.Date()`"
---

```{r warning=FALSE, message=FALSE}
#initial setup
library(tidyverse)
library(GGally)
library(car)

setwd("/Users/home/Downloads/5. Github Public Repos/Spotify Analysis (Stats 2 Project)")
spotify <- read_csv("data/Spotify-2000.csv")
```

```{r}
#select the needed data & rename some columns
spotify_smlr <- spotify %>%
  select(Popularity, Acousticness, Speechiness, `Length (Duration)`,
         Valence, Liveness, `Loudness (dB)`, Energy,
         `Beats Per Minute (BPM)`, `Top Genre`, Danceability) %>%
  rename(Loudness = `Loudness (dB)`,
         BPM = `Beats Per Minute (BPM)`,
         Length = `Length (Duration)`,
         Genre = `Top Genre`)

spotify_smlr <- spotify_smlr %>%
  mutate(Genre = case_when(
    grepl("rock", Genre, ignore.case = TRUE) ~ "Rock",
    grepl("pop", Genre, ignore.case = TRUE) ~ "Pop",
    grepl("soul", Genre, ignore.case = TRUE) ~ "Soul",
    grepl("blues", Genre, ignore.case = TRUE) ~ "Blues",
    grepl("hip hop", Genre, ignore.case = TRUE) ~ "Hip Hop",
    TRUE ~ "Other"
  ))

spotify_smlr <- spotify_smlr %>%
  mutate(danceCat = case_when(
    Danceability >=50 ~ 1,
    Danceability <50 ~ 0
  ))
```

## Chi squared: Danceability & Genre

```{r, warning=FALSE}
table_genre_dance <- table(spotify_smlr$Genre, spotify_smlr$danceCat)

# Print the contingency table to see the counts
print(table_genre_dance)

# Run the chi-squared test
chi_squared_result <- chisq.test(table_genre_dance)

# Print the result of the chi-squared test
print(chi_squared_result)
```




## Popularity lm
### original lm
```{r fig.width=8, fig.height=8}
#checking for collinearity of all variables
ggcorr(data = spotify_smlr %>% select(-Genre, -danceCat),
       label = TRUE, label_round = 2, label_size = 6,
       size = 6, hjust = 0.75,
       layout.exp = 1)

#lm with all vars
popular_lm1 <- lm(Popularity ~ Acousticness + Speechiness + Length + Valence + Liveness + Loudness + BPM + Danceability + Energy + Genre,
                  data = spotify_smlr)
summary(popular_lm1)
```

### VIF

```{r}
#checking for multi-collinearity(not present):
vif(popular_lm1) #vif should be <5 for all vars
```

### Stepwise selection via AIC

```{r}
popular_lm2 <- step(popular_lm1, trace = TRUE) #change trace to see Stepwise steps
summary(popular_lm2)
```


## Danceability
### original lm

```{r fig.width=8, fig.height=8}
#checking for collinearity of all quantitative vars
ggcorr(data = spotify_smlr %>% select(-Genre, -danceCat),
       label = TRUE, label_round = 2, label_size = 6,
       size = 6, hjust = 0.75,
       layout.exp = 1)

#lm with all except Popularity
dance_lm1 <- lm(Danceability ~ Acousticness + Speechiness + Length + Valence + Liveness + Loudness + BPM + Energy + Genre,
                  data = spotify_smlr)
summary(dance_lm1)
```

### VIF

```{r}
#checking for multiple-collinearity
vif(dance_lm1)
```

### Stepwise selection via AIC

```{r}
#finding optimal model
dance_lm2 <- step(dance_lm1, trace = TRUE) #change trace to true to see Stepwise
#summary(dance_lm2)
```
