---
title: "Spotify Final Project"
author: "logan lapace"
date: "2024-05-09"
output: html_document
---

```{r}
library(ggplot2)
```

```{r}
spotify <- read.csv("Spotify-2000.csv")
head(spotify)

#check for missing values
print(paste("Missing values in the dataset:", sum(is.na(spotify))))
colnames(spotify)
```
Exploratory Data Analysis:


```{r}
#correlation matrix
correlation_matrix <- cor(spotify[c("Popularity", "Danceability", "Energy", "Loudness..dB.", "Liveness", "Valence", "Acousticness", "Speechiness")])
print(correlation_matrix)
```

```{r}
#scatter plot b/w Popularity and Danceability
ggplot(spotify, aes(x = Danceability, y = Popularity)) +
  geom_point() +
  labs(x = "Danceability", y = "Popularity", title = "Scatter Plot of Danceability vs. Popularity")

#scatter plot b/w Popularity and Energy
ggplot(spotify, aes(x = Energy, y = Popularity)) +
  geom_point() +
  labs(x = "Energy", y = "Popularity", title = "Scatter Plot of Energy vs. Popularity")
```

```{r}
#popularity distribution
ggplot(spotify, aes(x = Popularity)) +
  geom_density(binwidth = 5, fill = "skyblue", color = "black") +
  labs(x = "Popularity", y = "Frequency", title = "Distribution of Popularity")

#danceability distribution
ggplot(spotify, aes(x = Danceability)) +
  geom_density(fill = "skyblue", color = "black") +
  labs(x = "Danceability", y = "Density", title = "Density Plot of Danceability")
```

